# File was automatically generated by mrt_cmake_modules
#
# This file exports the following variables:
# util_testing_ros_LIBRARIES: Library targets that should be linked against
# util_testing_ros_EXPORTED_TARGETS: As required by catkin
# util_testing_ros_EXPORTS_TARGETS: To indicate this package exports targets instead of plain libraries


####### Expanded from @PACKAGE_INIT@ by configure_package_config_file() #######
####### Any changes to this file will be overwritten by the next CMake run ####
####### The input file was packageConfig.cmake.in                            ########

get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

####################################################################################

set(util_testing_ros_LIBRARIES util_testing_ros::util_testing_ros;util_testing_ros::util_testing_ros_compiler_flags)  # things that dependend packages should link against

# catkin wants this. Don't bother with it.
set(util_testing_ros_EXPORTED_TARGETS)

# mark this as a catkin project
set(util_testing_ros_FOUND_CATKIN_PROJECT TRUE)
set(util_testing_ros_EXPORTS_TARGETS TRUE)

macro(_init_package_dependencies)
    # gets all targets that this package export_depends on and sets var to the name of these targets.
    # because this config file might be used recursively we have to be extra careful that variables set here do not affect each other
    if(TARGET util_testing_ros::auto_deps_export)
        return()
    endif()
    if(NOT EXISTS "${CMAKE_CURRENT_LIST_DIR}/auto_dep_vars.cmake")
        message(FATAL_ERROR "Project util_testing_ros did not export its dependencies properly! No auto_dep file was found.")
    endif()
    # Resolve deps in the same style they were resolved when this project was built
    include("${CMAKE_CURRENT_LIST_DIR}/auto_dep_vars.cmake") # sets _util_testing_ros_EXPORT_PACKAGES_

    set(util_testing_rosAutoDeps_PREFIX "util_testing_ros")
    set(util_testing_rosAutoDeps_NO_CATKIN_EXPORT TRUE) # disable variable export because catkin is not listening here
    if(NOT mrt_cmake_modules_FOUND)
        # We need the mrt_cmake_modules because they provide extra CMake Modules for finding thirdparty stuff
        find_package(mrt_cmake_modules REQUIRED)
    endif()
    find_package(util_testing_rosAutoDeps REQUIRED
        COMPONENTS ${_util_testing_ros_EXPORT_PACKAGES_}
        PATHS ${CMAKE_CURRENT_LIST_DIR} NO_DEFAULT_PATH
        )
    if(NOT OpenMP_FOUND)
        find_package(OpenMP) # openmp is by default always a dependency
    endif()
    unset(util_testing_rosAutoDeps_PREFIX)
    unset(util_testing_rosAutoDeps_NO_CATKIN_EXPORT)
endmacro()

if(util_testing_ros_LIBRARIES)
    _init_package_dependencies()
endif()

# add the targets
if(EXISTS "${CMAKE_CURRENT_LIST_DIR}/util_testing_rosTargets.cmake")
    include("${CMAKE_CURRENT_LIST_DIR}/util_testing_rosTargets.cmake")
endif()

# add dependencies to other things generated by this package
set(util_testing_ros_targets )
if(util_testing_ros_targets AND NOT TARGET util_testing_ros::mrt_exported_targets)
    set(namespaced_exported_targets)
    foreach(t ${util_testing_ros_targets})
        if(NOT TARGET ${target})
            add_library(util_testing_ros::${t} INTERFACE IMPORTED)
            list(APPEND namespaced_exported_targets util_testing_ros::${t})
        else()
            list(APPEND namespaced_exported_targets ${t})
        endif()
    endforeach()
    add_library(util_testing_ros::mrt_exported_targets INTERFACE IMPORTED)
    add_dependencies(util_testing_ros::mrt_exported_targets ${namespaced_exported_targets})
    list(APPEND util_testing_ros_LIBRARIES util_testing_ros::mrt_exported_targets)
    unset(namespaced_exported_targets)
endif()

set(util_testing_ros_EXTRAS_FILE )
if(util_testing_ros_EXTRAS_FILE)
    include(${CMAKE_CURRENT_LIST_DIR}/${util_testing_ros_EXTRAS_FILE})
endif()
unset(util_testing_ros_EXTRAS_FILE)
unset(util_testing_ros_targets)
